version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: crm_postgres
    restart: always
    ports:
       - 5432:5432
    environment:
       - POSTGRES_DB=cms_db
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=password
       - PGUSER=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready"]
       interval: 10s
       timeout: 5s
       retries: 5
       start_period: 15s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: pyeditorial:0.9
    container_name: crm_app
    restart: always
    ports:
      - 80:8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - dev.env