version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: crm_postgres
    restart: always
    ports:
       - 5432:5432
    environment:
       - POSTGRES_DB=cms_db
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=password
       - PGUSER=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
       test: ["CMD-SHELL", "pg_isready"]
       interval: 10s
       timeout: 5s
       retries: 5
       start_period: 15s

  web:
    build:
      context: .
      dockerfile: python.Dockerfile
    image: pyeditorial:0.9
    container_name: crm_app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - db